### ISSUE TITLE
Installation fails

### ISSUE THREAD

**Issue by jbusecke** [pgierz/jupyterlab_netcdfviewer#1]
Hi, 
I just tried to install the extension but it fails with `ValueError: "jupyterlab_netcdfviewer" is not a valid npm package` (more detailed error below).

Is there a dependency that I am missing?

Cheers

```
$ jupyter labextension install jupyterlab_netcdfviewer --debug
Searching ['/home/jbusecke', '/home/jbusecke/.jupyter', '/home/jbusecke/code/miniconda/etc/jupyter', '/usr/local/etc/jupyter', '/etc/jupyter'] for config files
Looking for jupyter_config in /etc/jupyter
Looking for jupyter_config in /usr/local/etc/jupyter
Looking for jupyter_config in /home/jbusecke/code/miniconda/etc/jupyter
Looking for jupyter_config in /home/jbusecke/.jupyter
Looking for jupyter_config in /home/jbusecke
Node v11.14.0

> /home/jbusecke/code/miniconda/bin/npm pack jupyterlab_netcdfviewer
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/jupyterlab_netcdfviewer - Not found
npm ERR! 404
npm ERR! 404  'jupyterlab_netcdfviewer@latest' is not in the npm registry.
npm ERR! 404 Your package name is not valid, because
npm ERR! 404  1. name can only contain URL-friendly characters
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/jbusecke/.npm/_logs/2019-07-09T18_00_05_322Z-debug.log
Traceback (most recent call last):

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 77, in start
    ans = self.run_task()

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 106, in run_task
    for arg in self.extra_args

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 106, in <listcomp>
    for arg in self.extra_args

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 219, in install_extension
    return handler.install_extension(extension)

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 418, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1250, in _install_extension
    info = self._extract_package(extension, tempdir)

  File "/home/jbusecke/code/miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1321, in _extract_package
    raise ValueError(msg % source)

ValueError: "jupyterlab_netcdfviewer" is not a valid npm package


Errored, use --debug for full output:
ValueError: "jupyterlab_netcdfviewer" is not a valid npm package
```

**Comment by pgierz** [comment]
Hi,

to be honest this was a holiday project a few years back which I've put on the back burner due to more pressing issues (e.g. papers...)

If this plugin is something you or your colleagues are interested in, I'd be very happy to restart it: something akin to `ncdump` directly from jupyter would be awesome to have in my opinion. I can't really say how much quickly I could get it running again though.

As to your error message: I never actually published the package on npm, so you'd need to install it from source.

Cheers,
Paul

**Comment by jbusecke** [comment]
Gotta publish! I hear you. 
Id personally love to have this functionality, and I can certainly recommend it to a bunch of colleagues!

Ill try the manual install and report back!
